### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lyandeveloper** [lyandeveloper/Hollytel#2]
- [ ] **Mobile**
   - [x] Authentication System
   - [x] Loggout
   - [x] Persist login
   - [x] Loading Screen
   - [ ] Create a account 
   - [ ] Create a hotel booking
   - [ ] List relevants hotels
   - [ ] List all hotels
   - [ ] Add a hotel as a favorite
   - [ ] Update a booking
   - [ ] Cancel a booking
   - [ ] When touch in a hotel, show it's information
   - [ ] Update user profile
